server:
  port: 9090

spring:
  application:
    name: ProductMicroservice
  kafka:
    producer:
      properties:
        enable:
          idempotence: true # by default, it is set to true, but it can de disable by conflicting values of other properties
        max:
          in:
            flight:
              request:
                per:
                  connection: 5 # should be less than 5 for idempotence to work
        retry:
          backoff:
            ms: 1000 # default is 100ms
        linger:
          ms: 100 # this property specifies the max time the producer will wait and buffer data before sending
          # a batch of messages, default is 0.
        request:
          timeout:
            ms: 10000 # max time to wait after sending a request, default value is 30000
        delivery:
          timeout:
            ms: 20000 # default value is 2 minutes
            # it should be >= linger.ms + request.timeout.ms
      bootstrap-server:
        - localhost:9092
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      Below property is used to get acknowledge from all the brokers,
#      kafka will wait for acknowledgement from insync-replicas only
      acks: all # should be all for idempotence to work
#      acks: 1
      retries:  12 # default value is 2147483747, should be positive integer for idempotence to work

product:
  created:
    topic:
      name: product-created-events-topic
