server:
  port: 9090

spring:
  application:
    name: ProductMicroservice
  kafka:
    producer:
      bootstrap-server:
        localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      Below property is used to get acknowledge from all the brokers,
#      kafka will wait for acknowledgement from insync-replicas only
#      acks: all
      acks: 1

product:
  created:
    topic:
      name: product-created-events-topic
